# -*- coding: utf-8 -*-
"""Análise Olist: Storytelling de Dados - Versão Premium

Automatically generated by Colab.
"""

import streamlit as st
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go

# --- CONFIGURAÇÃO DA PÁGINA ---
st.set_page_config(page_title="Olist Storytelling", layout="wide", page_icon="📦")

# --- PALETA DE CORES E TEMA ---
COLOR_PRIMARY = "#FF9900"  # Olist Orange
COLOR_SECONDARY = "#2E86C1" # Olist Blue
COLOR_ACCENT = "#28B463"    # Green for positive
COLOR_BG = "#F9F9F9"

# Função para padronizar o layout dos gráficos
def format_plot(fig):
    fig.update_layout(
        plot_bgcolor="white",
        paper_bgcolor="white",
        font_family="Arial",
        title_font_size=20,
        title_font_color="#333",
        xaxis=dict(showgrid=False, linecolor='black'),
        yaxis=dict(showgrid=True, gridcolor='#eee', linecolor='white'),
        hovermode="x unified"
    )
    return fig

# --- ESTILIZAÇÃO CSS CUSTOMIZADA ---
st.markdown(f"""
<style>
    .main-header {{
        font-family: 'Helvetica Neue', sans-serif;
        font-size: 3rem;
        color: {COLOR_PRIMARY};
        text-align: center;
        font-weight: 800;
        text-shadow: 1px 1px 2px rgba(0,0,0,0.1);
    }}
    .sub-header {{
        font-size: 1.2rem;
        color: #555;
        text-align: center;
        margin-bottom: 2rem;
    }}
    .metric-container {{
        background-color: white;
        padding: 15px;
        border-radius: 10px;
        box-shadow: 0 4px 6px rgba(0,0,0,0.1);
        text-align: center;
    }}
    .insight-box {{
        background-color: #FFF8E1; /* Light Orange/Yellow */
        border-left: 5px solid {COLOR_PRIMARY};
        padding: 20px;
        border-radius: 8px;
        margin: 15px 0;
        font-size: 1.05rem;
        box-shadow: 0 2px 4px rgba(0,0,0,0.05);
    }}
</style>
""", unsafe_allow_html=True)

# --- 1. CARREGAMENTO E PREPARAÇÃO DOS DADOS ---
@st.cache_data
def load_data():
    # Carregando datasets
    try:
        orders = pd.read_csv('olist_orders_dataset.csv')
        items = pd.read_csv('olist_order_items_dataset.csv')
        products = pd.read_csv('olist_products_dataset.csv')
        payments = pd.read_csv('olist_order_payments_dataset.csv')
        reviews = pd.read_csv('olist_order_reviews_dataset.csv')
        customers = pd.read_csv('olist_customers_dataset.csv')

        # Conversão de datas
        date_cols = ['order_purchase_timestamp', 'order_approved_at',
                     'order_delivered_carrier_date', 'order_delivered_customer_date',
                     'order_estimated_delivery_date']
        for col in date_cols:
            orders[col] = pd.to_datetime(orders[col])

        # Merge Otimizado
        df = orders.merge(items, on='order_id', how='left')
        df = df.merge(products, on='product_id', how='left')
        df = df.merge(customers, on='customer_id', how='left')
        df = df.merge(reviews, on='order_id', how='left')

        return df, orders, items, payments, reviews, products, customers
    except FileNotFoundError as e:
        return None, None, None, None, None, None, None

df, orders, items, payments, reviews, products, customers = load_data()

if df is None:
    st.error("Arquivos CSV não encontrados. Por favor, verifique se os arquivos 'olist_*.csv' estão no diretório.")
    st.stop()

# --- HEADER ---
st.markdown('<div class="main-header">O E-commerce Brasileiro em Números</div>', unsafe_allow_html=True)
st.markdown('<div class="sub-header">Uma Análise Visual Interativa com dados da Olist</div>', unsafe_allow_html=True)

# Métricas Rápidas com Design Limpo
c1, c2, c3, c4 = st.columns(4)
with c1:
    st.metric("📦 Total de Pedidos", f"{orders.shape[0]:,}".replace(",", "."))
with c2:
    val = items['price'].sum()
    st.metric("💰 Receita Total", f"R$ {val:,.2f}".replace(",", "X").replace(".", ",").replace("X", "."))
with c3:
    val_avg = items['price'].mean()
    st.metric("🏷️ Ticket Médio", f"R$ {val_avg:.2f}".replace(".", ","))
with c4:
    st.metric("🏙️ Cidades Atendidas", f"{customers['customer_city'].nunique()}")

st.markdown("---")

# --- CAPÍTULO 1: A EVOLUÇÃO TEMPORAL ---
st.header("📈 1. Sazonalidade e Crescimento")

# Preparação
orders['month_year'] = orders['order_purchase_timestamp'].dt.to_period('M')
sales_per_month = df.groupby(df['order_purchase_timestamp'].dt.to_period('M'))['price'].sum().reset_index()
sales_per_month['order_purchase_timestamp'] = sales_per_month['order_purchase_timestamp'].dt.to_timestamp()

col_chart, col_txt = st.columns([2, 1])

with col_chart:
    fig_time = px.area(sales_per_month, x='order_purchase_timestamp', y='price',
                       title='<b>Evolução da Receita Mensal</b>',
                       labels={'order_purchase_timestamp': 'Data', 'price': 'Receita'},
                       color_discrete_sequence=[COLOR_SECONDARY])
    
    # Adicionar anotação da Black Friday
    fig_time.add_vrect(x0="2017-11-01", x1="2017-11-30", 
                       annotation_text="Black Friday", annotation_position="top left",
                       fillcolor=COLOR_ACCENT, opacity=0.2, line_width=0)
    
    # Formatação de eixo Y para Moeda
    fig_time.update_yaxes(tickprefix="R$ ", showgrid=True)
    fig_time = format_plot(fig_time)
    st.plotly_chart(fig_time, use_container_width=True)

with col_txt:
    st.markdown("### ⚡ O Efeito Black Friday")
    st.write("A linha de tendência revela não apenas o crescimento orgânico, mas a **explosão de demanda** em Novembro.")
    st.markdown(f"""
    <div class="insight-box">
        <strong>Insight Estratégico:</strong><br>
        O pico de 2017 foi um teste de estresse logístico. Para o varejo brasileiro, 
        Novembro não é apenas um mês de vendas, é o mês que define o lucro anual.
    </div>
    """, unsafe_allow_html=True)

st.markdown("---")

# --- CAPÍTULO 2: GEOGRAFIA ---
st.header("🗺️ 2. Geografia e Logística")

col_geo1, col_geo2 = st.columns([3, 2])

# Dados
orders_by_state = customers['customer_state'].value_counts().reset_index()
orders_by_state.columns = ['Estado', 'Pedidos']
orders_by_state = orders_by_state.sort_values(by='Pedidos', ascending=True) # Sort for bar chart

with col_geo1:
    # Gráfico de Barras Horizontais Limpo
    fig_bar_state = px.bar(orders_by_state.tail(10), x='Pedidos', y='Estado',
                           title="<b>Top 10 Estados com Mais Pedidos</b>",
                           text='Pedidos',
                           orientation='h',
                           color='Pedidos',
                           color_continuous_scale='Oranges')
    
    fig_bar_state.update_traces(texttemplate='%{text:.2s}', textposition='outside')
    fig_bar_state.update_layout(xaxis_title=None, yaxis_title=None)
    fig_bar_state = format_plot(fig_bar_state)
    st.plotly_chart(fig_bar_state, use_container_width=True)

with col_geo2:
    # Análise de Frete
    freight_state = df.groupby('customer_state')['freight_value'].mean().sort_values(ascending=False).head(5).reset_index()
    
    st.markdown("### 🚛 O Custo da Distância")
    st.write("Enquanto SP domina o volume, o Norte e Nordeste pagam a conta do frete.")
    
    # Tabela estilizada
    st.markdown("**Estados com Frete Médio Mais Caro:**")
    st.dataframe(
        freight_state.style.format({"freight_value": "R$ {:.2f}"})
        .background_gradient(cmap='Reds', subset=['freight_value']),
        hide_index=True, use_container_width=True
    )
    
    st.markdown(f"""
    <div class="insight-box">
        <strong>Oportunidade:</strong><br>
        Criar Centros de Distribuição (CDs) no Nordeste (ex: PE ou BA) poderia reduzir o frete médio em até 40%, desbloqueando um mercado reprimido.
    </div>
    """, unsafe_allow_html=True)

st.markdown("---")

# --- CAPÍTULO 3: PRODUTOS ---
st.header("🛍️ 3. Categorias Mais Vendidas")

top_categories = df['product_category_name'].value_counts().head(10).reset_index()
top_categories.columns = ['Categoria', 'Qtd Vendas']

fig_cat = px.bar(top_categories, x='Categoria', y='Qtd Vendas',
                 title='<b>Top 10 Categorias</b>',
                 color='Qtd Vendas', 
                 color_continuous_scale='Blues',
                 text='Qtd Vendas')

fig_cat.update_traces(texttemplate='%{text:.2s}', textposition='outside')
fig_cat.update_layout(xaxis_tickangle=-45)
fig_cat = format_plot(fig_cat)
st.plotly_chart(fig_cat, use_container_width=True)

st.markdown("---")

# --- CAPÍTULO 4: REVIEWS VS ENTREGA ---
st.header("⭐ 4. A Experiência do Cliente")

# Dados
df_delivered = df[df['order_status'] == 'delivered'].copy()
df_delivered['delivery_days'] = (df_delivered['order_delivered_customer_date'] - df_delivered['order_purchase_timestamp']).dt.days
avg_time_score = df_delivered.groupby('review_score')['delivery_days'].mean().reset_index()

col_rev1, col_rev2 = st.columns([2, 1])

with col_rev1:
    fig_rev = px.bar(avg_time_score, x='review_score', y='delivery_days',
                     title='<b>Impacto do Atraso na Nota (Score)</b>',
                     color='delivery_days', 
                     color_continuous_scale='RdYlGn_r', # Red is high (bad), Green is low (good)
                     text='delivery_days',
                     labels={'review_score': 'Avaliação (1-5)', 'delivery_days': 'Dias Médios'})
    
    fig_rev.update_traces(texttemplate='%{text:.1f} dias', textposition='outside')
    # Adicionar linha de tolerância
    fig_rev.add_hline(y=15, line_dash="dot", line_color="red", annotation_text="Zona de Perigo (>15 dias)")
    fig_rev = format_plot(fig_rev)
    st.plotly_chart(fig_rev, use_container_width=True)

with col_rev2:
    st.markdown("### ⚠️ A Regra dos 15 Dias")
    st.write("Os dados mostram uma correlação direta: **Clientes felizes recebem em ~10 dias.**")
    st.write("Quando a entrega passa de duas semanas, a nota despenca para 1 ou 2 estrelas.")
    
    with st.expander("🔍 Ver reclamações reais (Score 1)"):
        bad_reviews = df[df['review_score'] == 1]['review_comment_message'].dropna().sample(5).values
        for comment in bad_reviews:
            st.warning(f'"{comment}"')

st.markdown("---")

# --- CAPÍTULO 5: PAGAMENTOS ---
st.header("💳 5. Perfil de Pagamento")

payment_types = payments['payment_type'].value_counts().reset_index()
payment_types.columns = ['Tipo', 'Total']

col_pay1, col_pay2 = st.columns(2)

with col_pay1:
    # Gráfico de Rosca (Donut) é mais moderno que Pizza
    fig_pie = px.pie(payment_types, values='Total', names='Tipo', hole=0.5,
                     title='<b>Meios de Pagamento</b>',
                     color_discrete_sequence=px.colors.qualitative.Pastel)
    fig_pie.update_traces(textposition='inside', textinfo='percent+label')
    fig_pie = format_plot(fig_pie)
    st.plotly_chart(fig_pie, use_container_width=True)

with col_pay2:
    # Gráfico de parcelas substituindo o st.bar_chart nativo
    installments_data = payments[payments['payment_type'] == 'credit_card']['payment_installments'].value_counts().head(10).reset_index()
    installments_data.columns = ['Parcelas', 'Contagem']
    installments_data = installments_data.sort_values(by='Parcelas')
    
    fig_inst = px.bar(installments_data, x='Parcelas', y='Contagem',
                      title='<b>Parcelamento no Crédito</b>',
                      color_discrete_sequence=[COLOR_PRIMARY])
    fig_inst.update_xaxes(type='category') # Tratar parcelas como categorias (1x, 2x...)
    fig_inst = format_plot(fig_inst)
    st.plotly_chart(fig_inst, use_container_width=True)

# --- FOOTER ---
st.markdown("---")
st.markdown(f"""
<div style="text-align: center; color: #888;">
    <small>Desenvolvido com Streamlit e Plotly | Dados públicos da Olist</small>
</div>
""", unsafe_allow_html=True)
